### ISSUE TITLE
Calibration can fail

### ISSUE THREAD

**Issue by davidadkins1** [Seeed-Studio/Grove_3_Axis_Digital_Gyro#1]
Calibration can fail because the variables x_offset_temp, y_offset_temp, and z_offset_temp, in ITG3200::zeroCalibrate(), are not initialized to zero before use. I have observed this problem using Arduino version 1.6.5 on a Mega2560 board. This change resolves the issue:

int16_t x_offset_temp = 0; 
int16_t y_offset_temp = 0; 
int16_t z_offset_temp = 0;

**Comment by KillingJacky** [comment]
Thanks David. It's fixed.
